groups:
- name: all
  jobs:
  - gp_xerces
  - gpos_centos6_release
  - orca_centos6_release
  - build_gpdb_centos6
  - gpdb_icg
resources:
- name: bin_gpdb_with_orca_centos6
  type: s3
  source:
    access_key_id: {{aws-access-key-id}}
    bucket: gporca-concourse-bucket
    region_name: us-west-2
    secret_access_key: {{aws-secret-access-key}}
    versioned_file: bin_gpdb_with_orca_centos6.tar.gz
- name: gpos_src
  type: git
  source:
    branch: master
    private_key: {{gpdb_deploy_key}}
    uri: git@github.com:greenplum-db/gpos.git
- name: orca_src
  type: git
  source:
    branch: master
    private_key: {{gpdb_deploy_key}}
    uri: git@github.com:greenplum-db/gporca.git
- name: gpdb_src
  type: git
  source:
    branch: master
    private_key: {{gpdb_deploy_key}}
    uri: git@github.com:greenplum-db/gpdb.git
- name: xerces_patch
  type: git
  source:
    branch: master
    paths:
    - patches/xerces-c-gpdb.patch
    - concourse/xerces-c
    - concourse/package_tarball.bash
    private_key: {{gpdb_deploy_key}}
    uri: git@github.com:greenplum-db/gporca.git
- name: bin_xerces_centos6
  type: s3
  source:
    access_key_id: {{aws-access-key-id}}
    bucket: gporca-concourse-bucket
    region_name: us-west-2
    secret_access_key: {{aws-secret-access-key}}
    versioned_file: bin_xerces_centos6.tar.gz
- name: bin_gpos_centos6_release
  type: s3
  source:
    access_key_id: {{aws-access-key-id}}
    bucket: gporca-concourse-bucket
    region_name: us-west-2
    secret_access_key: {{aws-secret-access-key}}
    versioned_file: bin_gpos_centos6_release.tar.gz
- name: bin_orca_centos6_release
  type: s3
  source:
    access_key_id: {{aws-access-key-id}}
    bucket: gporca-concourse-bucket
    region_name: us-west-2
    secret_access_key: {{aws-secret-access-key}}
    versioned_file: bin_orca_centos6_release.tar.gz
resource_types: []
jobs:
- name: gp_xerces
  max_in_flight: 2
  plan:
  - get: xerces_patch
    trigger: true
  - aggregate:
    - task: build_centos6
      file: xerces_patch/concourse/xerces-c/build_xerces_centos6.yml
  - aggregate:
    - task: package_tarball_centos6
      file: xerces_patch/concourse/xerces-c/package_tarball_centos6.yml
  - aggregate:
    - put: bin_xerces_centos6
      params:
        from: package_tarball_centos6/bin_xerces_centos6.tar.gz
- name: gpos_centos6_release
  max_in_flight: 2
  plan:
  - get: gpos_src
    trigger: true
  - task: build_and_test_centos6_release
    file: gpos_src/concourse/build_centos6_release.yml
  - task: package_tarball_centos6_release
    file: gpos_src/concourse/package_tarball_centos6_release.yml
  - put: bin_gpos_centos6_release
    params:
      from: package_tarball_centos6_release/bin_gpos_centos6_release.tar.gz
- name: orca_centos6_release
  max_in_flight: 2
  plan:
  - get: orca_src
    trigger: true
  - get: bin_gpos_centos6_release
    passed:
    - gpos_centos6_release
    trigger: true
  - get: bin_xerces_centos6
    passed:
    - gp_xerces
    trigger: true
  - task: build_and_test_centos6_release
    file: orca_src/concourse/build_and_test_centos6_release.yml
  - task: package_tarball_centos6_release
    file: orca_src/concourse/package_tarball_centos6_release.yml
  - put: bin_orca_centos6_release
    params:
      from: package_tarball_centos6_release/bin_orca_centos6_release.tar.gz
- name: build_gpdb_centos6
  max_in_flight: 1
  plan:
  - aggregate:
    - get: bin_gpos_centos6_release
      passed:
      - gpos_centos6_release
    - get: bin_orca_centos6_release
      passed:
      - orca_centos6_release
      trigger: true
    - get: bin_xerces_centos6
      passed:
      - gp_xerces
    - get: gpdb_src
      params:
        submodules: none
  - task: build_with_orca
    input_mapping:
      bin_orca: bin_orca_centos6_release
      bin_gpos: bin_gpos_centos6_release
      bin_xerces: bin_xerces_centos6
    file: gpdb_src/concourse/build_with_orca.yml
  - task: package_tarball_centos6
    file: gpdb_src/concourse/package_tarball.yml
  - put: bin_gpdb_with_orca_centos6
    params:
      from: package_tarball/bin_gpdb.tar.gz
- name: gpdb_icg
  max_in_flight: 1
  plan:
  - aggregate:
    - get: gpdb_src
      params:
        submodules: none
    - get: bin_gpdb_with_orca_centos6
      passed:
      - build_gpdb_centos6
      trigger: true
    - get: bin_gpos_centos6_release
      passed:
      - gpos_centos6_release
    - get: bin_orca_centos6_release
      passed:
      - orca_centos6_release
    - get: bin_xerces_centos6
      passed:
      - gp_xerces
  - aggregate:
    - task: test_with_orca
      input_mapping:
        bin_orca: bin_orca_centos6_release
        bin_gpos: bin_gpos_centos6_release
        bin_xerces: bin_xerces_centos6
        bin_gpdb: bin_gpdb_with_orca_centos6
      file: gpdb_src/concourse/test_with_orca.yml
      timeout: 1h30m
